name: "@labset/task-pool-executor Build and Test"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn format:check
      - run: yarn lint
      - run: yarn test
      - run: yarn build
