name: "@labset/task-pool-executor Build and Test"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: yarn
      - run: yarn format:check
      - run: yarn lint
      - run: yarn test
      - run: yarn build
